### Create a feedback
POST {{$dotenv LOCAL_HOST}}/chitubox-manual-feedbacks
Content-Type: application/json

{
	"pageId": "/en-US/chitubox-basic/v2.0.0/introduction",
	"url": "manual.chitubox.com/en-US/docs/chitubox-basic/latest/introduction",
	"payload": "USEFUL"
}

### Find feedbacks with startDate and endDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET {{$dotenv LOCAL_HOST}}/chitubox-manual-feedbacks
	?startDate=2023-02-08T00:00:00.000Z
	&endDate=2023-02-08T23:59:59.999Z
Authorization: {{$dotenv AUTHORIZATION}}

### Find feedbacks with startDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET {{$dotenv LOCAL_HOST}}/chitubox-manual-feedbacks
	?startDate=2023-02-08T00:00:00.000Z
Authorization: {{$dotenv AUTHORIZATION}}

### Find feedbacks with endDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET {{$dotenv LOCAL_HOST}}/chitubox-manual-feedbacks
	?endDate=2023-02-08T23:59:59.999Z
Authorization: {{$dotenv AUTHORIZATION}}
