
### Create a group
POST {{$dotenv LOCAL_HOST}}/member-groups
Content-Type: application/x-www-form-urlencoded
Authorization: {{$dotenv AUTHORIZATION}}

name=everyone

### Find member-groups
GET {{$dotenv LOCAL_HOST}}/member-groups
Authorization: {{$dotenv AUTHORIZATION}}

### Find a group
GET {{$dotenv LOCAL_HOST}}/member-groups/6
Authorization: {{$dotenv AUTHORIZATION}}

### Update a group
PATCH {{$dotenv LOCAL_HOST}}/member-groups/8
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"name": "everyone",
	"ownerId": "8b9136f6-902d-4799-b5c2-5f6caebac8b6",
	"memberIds": [
		"8b9136f6-902d-4799-b5c2-5f6caebac8b6",
		"59f73769-1794-4389-a731-8a774cb58bc0",
		"1f20ae40-c57c-4ff8-b244-8741cb2dfcfe",
		"663e6397-d15d-4fdb-813f-2ef99b2973f2"
	]
}

### Remove a group
DELETE {{$dotenv LOCAL_HOST}}/member-groups/5
Authorization: {{$dotenv AUTHORIZATION}}
