### Create a member
POST {{$dotenv LOCAL_HOST}}/members/create
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"email": "qwer@cbd-3d.com",
	"nickname": "Qwer",
	"password": "1234Abcd!"
}

### Find members
GET {{$dotenv LOCAL_HOST}}/members
	# ?email=KyUnG@cbd-3d.com
	# &nickname=Kyung
	# &roleIds=10
Authorization: {{$dotenv AUTHORIZATION}}

### Find members by ids
GET {{$dotenv LOCAL_HOST}}/members/ids
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"ids": [
		"8b9136f6-902d-4799-b5c2-5f6caebac8b6",
		"1f20ae40-c57c-4ff8-b244-8741cb2dfcfe"
	]
}

### Find me
GET {{$dotenv LOCAL_HOST}}/members/me
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

### Find a member
GET {{$dotenv LOCAL_HOST}}/members/8b9136f6-902d-4799-b5c2-5f6caebac8b6
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

### Verify a member manually
PATCH {{$dotenv LOCAL_HOST}}/members/member-verification/449ed90f-59d3-4a6f-b39d-033bb13da350
Authorization: {{$dotenv AUTHORIZATION}}

### Update a member profile
PATCH {{$dotenv LOCAL_HOST}}/members/profile/8b9136f6-902d-4799-b5c2-5f6caebac8b6
Content-Type: application/x-www-form-urlencoded
Authorization: {{$dotenv AUTHORIZATION}}

nickname=Kyung

### Update a member email
PATCH {{$dotenv LOCAL_HOST}}/members/email/8b9136f6-902d-4799-b5c2-5f6caebac8b6
Content-Type: application/x-www-form-urlencoded
Authorization: {{$dotenv AUTHORIZATION}}

email=kyung@cbd-3d.com

### Update member-roles
PATCH {{$dotenv LOCAL_HOST}}/members/roles/8b9136f6-902d-4799-b5c2-5f6caebac8b6
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"roleIds": [
	]
}

### Update member password
PATCH {{$dotenv LOCAL_HOST}}/members/password/56b90810-3793-400e-92af-6d97f495adb7
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"oldPassword": "1234Abcd!",
	"newPassword": "4321Abcd!"
}

# Note, pure HTTP syntax can not select a file to upload using
# multipart/form-data. Use Insomnia or Postman instead.
### Update member avatar
PUT {{$dotenv LOCAL_HOST}}/members/updateAvatar
Content-Type: multipart/form-data; boundary=REST-CLIENT-BOUNDARY
Authorization: {{$dotenv AUTHORIZATION}}

--REST-CLIENT-BOUNDARY
Content-Disposition: form-data; name="file"; filename="938-536x354.png"
Content-Type: image/png

< xxxxx
--REST-CLIENT-BOUNDARY--

### Freeze a member
PATCH  {{$dotenv LOCAL_HOST}}/members/freeze/430e9765-a771-4ef0-8fe4-dac8f6dfbb0f
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"isFrozen": true
}

### Delete a member
DELETE {{$dotenv LOCAL_HOST}}/members/da46993e-ca6e-4ed4-94d7-29380e9f71bc
Authorization: {{$dotenv AUTHORIZATION}}
