### Create server settings
# DANGER! This should only be triggered during the server seeding.
POST {{$dotenv LOCAL_HOST}}/server-settings
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"allowPublicSignUp": true,
	"allowGoogleSignIn": true
}

### Check is sign up available
GET {{$dotenv LOCAL_HOST}}/server-settings/isSignUpAvailable
Content-Type: application/json

### Get server settings
GET {{$dotenv LOCAL_HOST}}/server-settings
Authorization: {{$dotenv AUTHORIZATION}}

### Update server settings
PATCH {{$dotenv LOCAL_HOST}}/server-settings
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"allowPublicSignUp": true,
	"allowGoogleSignIn": false
}
