-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "templateScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "EventTemplate" ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;
