export enum Permissions {
	/* Server settings */
	GET_SERVER_SETTING = "GET_SERVER_SETTING",
	UPDATE_SERVER_SETTING = "UPDATE_SERVER_SETTING",

	/* Auth permissions */
	CREATE_USER = "CREATE_USER",

	/* User permissions */
	UPDATE_USER = "UPDATE_USER",
	UPDATE_ME = "UPDATE_ME",
	TRANSFER_ADMIN = "TRANSFER_ADMIN",
	GET_USERS = "GET_USERS",
	GET_ME = "GET_ME",
	DELETE_USER = "DELETE_USER",

	/* Role permissions */
	CREATE_ROLE = "CREATE_ROLE",
	UPDATE_ROLE = "UPDATE_ROLE",
	GET_ROLES = "GET_ROLES",
	DELETE_ROLE = "DELETE_ROLE",

	/* Group permissions */
	CREATE_GROUP = "CREATE_GROUP",
	UPDATE_GROUP = "UPDATE_GROUP",
	GET_GROUPS = "GET_GROUPS",
	DELETE_GROUP = "DELETE_GROUP",

	/* Permission permissions */
	GET_PERMISSIONS = "GET_PERMISSIONS",

	/* ========= Discord ========= */

	/* Create draw event */
	CREATE_DISCORD_DRAW_CAMPAIGN = "CREATE_DISCORD_DRAW_CAMPAIGN",
	FIND_DISCORD_DRAW_CAMPAIGNS = "FIND_DISCORD_DRAW_CAMPAIGNS",
	GET_DISCORD_DRAW_CAMPAIGN = "GET_DISCORD_DRAW_CAMPAIGN",

	/* ====== CHITUBOX Manual ====== */
	FIND_CHITUBOX_MANUAL_FEEDBACKS = "FIND_CHITUBOX_MANUAL_FEEDBACKS",
}
