export enum Permissions {
	/* Server settings */
	GET_MEMBER_SERVER_SETTING = "GET_MEMBER_SERVER_SETTING",
	UPDATE_MEMBER_SERVER_SETTING = "UPDATE_MEMBER_SERVER_SETTING",

	/* Auth permissions */
	CREATE_MEMBER = "CREATE_MEMBER",

	/* Member permissions */
	UPDATE_MEMBER = "UPDATE_MEMBER",
	UPDATE_MEMBER_ME = "UPDATE_MEMBER_ME",
	TRANSFER_MEMBER_ADMIN = "TRANSFER_MEMBER_ADMIN",
	GET_MEMBERS = "GET_MEMBERS",
	GET_MEMBER_ME = "GET_MEMBER_ME",
	DELETE_MEMBER = "DELETE_MEMBER",

	/* Member role permissions */
	CREATE_MEMBER_ROLE = "CREATE_MEMBER_ROLE",
	UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE",
	GET_MEMBER_ROLES = "GET_MEMBER_ROLES",
	DELETE_MEMBER_ROLE = "DELETE_MEMBER_ROLE",

	/* Member group permissions */
	CREATE_MEMBER_GROUP = "CREATE_MEMBER_GROUP",
	UPDATE_MEMBER_GROUP = "UPDATE_MEMBER_GROUP",
	TRANSFER_MEMBER_GROUP_OWNER = "TRANSFER_MEMBER_GROUP_OWNER",
	GET_MEMBER_GROUPS = "GET_MEMBER_GROUPS",
	DELETE_MEMBER_GROUP = "DELETE_MEMBER_GROUP",

	/* Permission permissions */
	GET_PERMISSIONS = "GET_PERMISSIONS",

	/* ====== CHITUBOX Manual ====== */
	FIND_CHITUBOX_MANUAL_FEEDBACKS = "FIND_CHITUBOX_MANUAL_FEEDBACKS",
}
