### Check is seeded
GET {{$dotenv SERVER_HOST}}/auth/isSeeded

### Seed
POST {{$dotenv SERVER_HOST}}/auth/seed
Content-Type: application/json

{
	"email": "kyung@cbd-3d.com",
	"nickname": "Kyung",
	"password": "hdkmQ@m98M83"
}

### Check is sign-up available
GET {{$dotenv SERVER_HOST}}/auth/isSignUpAvailable

### Sign up
POST {{$dotenv SERVER_HOST}}/auth/signup
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"email": "zxcv4@cbd-3d.com",
	"nickname": "zxcv4",
	"password": "hdkmQ@m98M83"
}

### Sign in
POST {{$dotenv SERVER_HOST}}/auth/signin
Content-Type: application/json

{
	"email": "kyung.lee.official@gmail.com",
	"password": "hdkmQ@m98M83"
}

### Check is signed in
GET {{$dotenv SERVER_HOST}}/auth/isSignedIn
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}
