### Create a feedback
POST http://localhost:3001/chitubox-manual-feedbacks
Content-Type: application/json

{
	"url": "manual.chitubox.com",
	"payload": "USEFUL"
}

### Find feedbacks with startDate and endDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET http://localhost:3001/chitubox-manual-feedbacks
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"startDate": "2023-02-08",
	"endDate": "2023-02-08"
}

### Find feedbacks with startDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET http://localhost:3001/chitubox-manual-feedbacks
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"startDate": "2023-02-07"
}

### Find feedbacks with endDate
# Since the server timezone is always UTC (use `timedatectl` command to check), the front end need to convert dates to UTC before sending the request.
GET http://localhost:3001/chitubox-manual-feedbacks
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"endDate": "2023-02-07"
}
