@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5dW5nQGNiZC0zZC5jb20iLCJpYXQiOjE2NzU3NTYyNTgsImV4cCI6MTY3NTg0MjY1OH0.ICtWu9uEc5W13aE0aXzRJGJWWydj6y8U3X1eV4q3dRo

### Create a feedback
POST http://localhost:3001/chitubox-manual-feedbacks
Content-Type: application/json

{
	"url": "manual.chitubox.com",
	"payload": "USEFUL"
}
