
### Create a group
POST http://localhost:3001/groups
Content-Type: application/x-www-form-urlencoded
Authorization: {{$dotenv AUTHORIZATION}}

name=设计

### Find groups
GET http://localhost:3001/groups
Authorization: {{$dotenv AUTHORIZATION}}

### Find a group
GET http://localhost:3001/groups/6
Authorization: {{$dotenv AUTHORIZATION}}

### Update a group
PATCH http://localhost:3001/groups/7
Content-Type: application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"name": "设计",
	"ownerId": "8b9136f6-902d-4799-b5c2-5f6caebac8b6",
	"userIds": [
		"8b9136f6-902d-4799-b5c2-5f6caebac8b6",
		"59f73769-1794-4389-a731-8a774cb58bc0"
	]
}

### Remove a group
DELETE http://localhost:3001/groups/5
Authorization: {{$dotenv AUTHORIZATION}}
