### Update admin permissions
GET {{$dotenv SERVER_HOST}}/roles/updateAdminPermissions
Authorization: {{$dotenv AUTHORIZATION}}

### Create a role
POST {{$dotenv SERVER_HOST}}/roles
Content-Type: application/x-www-form-urlencoded
Authorization: {{$dotenv AUTHORIZATION}}

name=研发

### Find roles
GET {{$dotenv SERVER_HOST}}/roles
Authorization: {{$dotenv AUTHORIZATION}}

### Find a role by id
GET {{$dotenv SERVER_HOST}}/roles/17
Authorization: {{$dotenv AUTHORIZATION}}

### Update role by id
PATCH {{$dotenv SERVER_HOST}}/roles/11
Content-Type: application/application/json
Authorization: {{$dotenv AUTHORIZATION}}

{
	"permissions": [
		"GET_ROLES",
		"GET_PERMISSIONS",
		"GET_USERS",
		"GET_ME"
	],
	"userIds": [
		"59f73769-1794-4389-a731-8a774cb58bc0"
	]
}

### Delete a role
DELETE {{$dotenv SERVER_HOST}}/roles/13
Authorization: {{$dotenv AUTHORIZATION}}
